import Banner from "../components/Banner";
import Menu from "../components/Menu";
import { NextPage } from "next";
import Head from "next/head";
import LectureGroup from "@/components/lecture/LectureGroup";

const Detail: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />
      <Banner />
      <LectureGroup />
    </>
  );
};

export default Detail;
