import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <nav aria-label='fastcampus'>
        <h1>fastcampus</h1>
      </nav>
      <div role='banner'>
        <h1>배너</h1>
      </div>
      <div title='lectureList'>
        <h1>강의 목록</h1>
      </div>
    </>
  );
}
