import Head from "next/head";
import Menu from "../components/Menu";
import Banner from "../components/Banner";
import LectureGroup from "../components/lecture/LectureGroup";

const Index = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <Banner />
      <LectureGroup />
    </>
  );
};

export default Index;
